/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/modules/products/screens/products/products.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/cart/screens/edit-cart-item/edit-cart-item.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.component`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.component`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../src/modules/products/screens/products/products.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/modules/cart/screens/edit-cart-item/edit-cart-item.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.component`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.component`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../src/modules/products/screens/products/products.styles${`?${string}` | `#${string}` | ''}` | `/../src/modules/cart/screens/edit-cart-item/edit-cart-item.styles${`?${string}` | `#${string}` | ''}` | `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.component${`?${string}` | `#${string}` | ''}` | `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.styles${`?${string}` | `#${string}` | ''}` | `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.component${`?${string}` | `#${string}` | ''}` | `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/modules/products/screens/products/products.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../src/modules/cart/screens/edit-cart-item/edit-cart-item.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.component`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon/cart-icon-with-badge.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.component`; params?: Router.UnknownInputParams; } | { pathname: `/../src/shared/componetnts/header/components/cart-icon-with-badge/cart-icon-with-badge.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
