export enum NAVIGATION_KEYS {
	LOGIN = "LOGIN",
	SIGNUP = "SIGNUP",
	EMEIL_VERIFICATION = "EMEIL_VERIFICATION",
	REGISTERED_SUCCESSFULLY = "REGISTERED_SUCCESSFULLY",
	SETTINGS = "SETTINGS",
	ORDERS = "ORDERS",
	PRODUCTS = "RPODUCTS",
	SETTINGS_STACK = "SETTINGS_STACK",
	ORDERS_STACK = "ORDERS_STACK",
	PRODUCTS_STACK = "PRODUCTS_STACK",
	BOTTOM_TAB = "BOTTOM_TAB",
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.SIGNUP]: undefined;
	[NAVIGATION_KEYS.EMEIL_VERIFICATION]: { email: string };
	[NAVIGATION_KEYS.REGISTERED_SUCCESSFULLY]: undefined;
	[NAVIGATION_KEYS.SETTINGS]: undefined;
	[NAVIGATION_KEYS.ORDERS]: undefined;
	[NAVIGATION_KEYS.PRODUCTS]: undefined;
	[NAVIGATION_KEYS.SETTINGS_STACK]: undefined;
	[NAVIGATION_KEYS.ORDERS_STACK]: undefined;
	[NAVIGATION_KEYS.PRODUCTS_STACK]: undefined;
	[NAVIGATION_KEYS.BOTTOM_TAB]: undefined;
};
