export enum NAVIGATION_KEYS {
	LOGIN = "LOGIN",
	SIGNUP = "SIGNUP",
	EMEIL_VERIFICATION = "EMEIL_VERIFICATION",
	REGISTERED_SUCCESSFULLY = "REGISTERED_SUCCESSFULLY",
	SETTINGS = "SETTINGS",
	ORDERS = "ORDERS",
	ORDERS_DETAILS = "ORDERS_DETAILS",
	EDIT_ORDER = "EDIT_ORDER",
	PRODUCTS = "RPODUCTS",
	PRODUCT_INFORMATION = "PRODUCT_INFORMATION",
	CART = "CART",
	EDIT_CART_ITEM = "EDIT_CART_ITEM",
	CHANGE_PASSWORD = "CHANGE_PASSWORD",
	PERSONAL_INFO = "PERSONAL_INFO",
	FAQ = "FAQ",
	SETTINGS_STACK = "SETTINGS_STACK",
	ORDERS_STACK = "ORDERS_STACK",
	PRODUCTS_STACK = "PRODUCTS_STACK",
	BOTTOM_TAB = "BOTTOM_TAB",
	PAYMENT_SUCCESSFULLY = "PAYMENT_SUCCESSFULLY",
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.SIGNUP]: undefined;
	[NAVIGATION_KEYS.EMEIL_VERIFICATION]: { email: string };
	[NAVIGATION_KEYS.REGISTERED_SUCCESSFULLY]: undefined;
	[NAVIGATION_KEYS.SETTINGS]: undefined;
	[NAVIGATION_KEYS.ORDERS]: undefined;
	[NAVIGATION_KEYS.ORDERS_DETAILS]: { id: string };
	[NAVIGATION_KEYS.EDIT_ORDER]: { id: string };
	[NAVIGATION_KEYS.PRODUCTS]: undefined;
	[NAVIGATION_KEYS.PRODUCT_INFORMATION]: { id: string };
	[NAVIGATION_KEYS.CART]: undefined;
	[NAVIGATION_KEYS.EDIT_CART_ITEM]: { id: string };
	[NAVIGATION_KEYS.CHANGE_PASSWORD]: undefined;
	[NAVIGATION_KEYS.PERSONAL_INFO]: undefined;
	[NAVIGATION_KEYS.FAQ]: undefined;
	[NAVIGATION_KEYS.SETTINGS_STACK]: undefined;
	[NAVIGATION_KEYS.ORDERS_STACK]: undefined;
	[NAVIGATION_KEYS.PRODUCTS_STACK]: undefined;
	[NAVIGATION_KEYS.BOTTOM_TAB]: undefined;
	[NAVIGATION_KEYS.PAYMENT_SUCCESSFULLY]: undefined;
};
